basePath: /
definitions:
  models.ParsedRequest:
    properties:
      cookies:
        additionalProperties:
          type: string
        type: object
      get_params:
        additionalProperties:
          type: string
        type: object
      headers:
        additionalProperties:
          type: string
        type: object
      method:
        type: string
      path:
        type: string
      post_params:
        additionalProperties:
          type: string
        type: object
    type: object
  models.ParsedResponse:
    properties:
      body:
        type: string
      code:
        type: integer
      headers:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
    type: object
  models.Request:
    properties:
      createdAt:
        type: string
      id:
        type: string
      request:
        $ref: '#/definitions/models.ParsedRequest'
      response:
        $ref: '#/definitions/models.ParsedResponse'
    type: object
host: localhost:8000
info:
  contact: {}
  description: API server for Proxy
  title: API Proxy
  version: "1.0"
paths:
  /repeat/{id}:
    post:
      description: Resends the request and returns the result
      parameters:
      - description: Request ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ParsedResponse'
        "400":
          description: Invalid request ID
          schema:
            type: string
        "404":
          description: Request not found
          schema:
            type: string
        "500":
          description: Failed to repeat request
          schema:
            type: string
      summary: Repeat a request by ID
      tags:
      - requests
  /requests:
    get:
      description: Returns a list of all requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Request'
            type: array
        "500":
          description: Failed to fetch requests
          schema:
            type: string
      summary: Get all requests
      tags:
      - requests
  /requests/{id}:
    get:
      description: Returns a request by ID
      parameters:
      - description: Request ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Request'
        "400":
          description: Invalid request ID
          schema:
            type: string
        "404":
          description: Request not found
          schema:
            type: string
      summary: Get request by ID
      tags:
      - requests
swagger: "2.0"
